version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*github.com/spf13/cobra.Command).MarkFlagFilename
        - github.com/spf13/cobra.MarkFlagRequired
        - github.com/spf13/cobra.MarkFlagFilename
        - github.com/spf13/cobra.MarkFlagFilename
        - (*github.com/spf13/cobra.Command).Help
        - (*github.com/spf13/viper.Viper).BindPFlags
        - (*github.com/spf13/pflag.FlagSet).MarkHidden
    gocyclo:
      min-complexity: 20
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - hugeParam
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  settings:
    goimports:
      local-prefixes: github.com/elastic/ecctl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    tab:
      path: stderr
