version: "2"

linters:
  disable:
    - dupl
    - lll
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - wsl
    - mnd
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*github.com/spf13/cobra.Command).MarkFlagFilename
        - github.com/spf13/cobra.MarkFlagRequired
        - github.com/spf13/cobra.MarkFlagFilename
        - github.com/spf13/cobra.MarkFlagFilename
        - (*github.com/spf13/cobra.Command).Help
        - (*github.com/spf13/viper.Viper).BindPFlags
        - (*github.com/spf13/pflag.FlagSet).MarkHidden
    govet:
      check-shadowing: false
    gofmt:
      simplify: true
    golint:
      min-confidence: 0
    gocyclo:
      min-complexity: 20
    maligned:
      suggest-new: true
    misspell:
      locale: neutral
    goimports:
      local-prefixes: github.com/elastic/ecctl
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - hugeParam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - gocognit
      - path: cmd/platform/enrollment-token/command.go
        linters:
          - gosec
      - path: cmd/version.go
        linters:
          - gosec
      - path: cmd/deployment/search.go
        linters:
          - staticcheck
        text: "ST1005:"
    paths:
      - pkg/formatter/templates/bindata.go

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    paths:
      - pkg/formatter/templates/bindata.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    tab:
      path: stderr
