project_name: ecctl
before:
  hooks:
    - go mod download
release:
  github:
    owner: elastic
    name: ecctl
  name_template: '{{.Tag}}'
  draft: false
brews:
  - github:
      owner: elastic
      name: homebrew-ecctl
    commit_author:
      name: elasticloudbot
      email: cloud-tooling@elastic.co
    homepage: "https://github.com/elastic/ecctl"
    description: Elastic Cloud Control, the official Elastic Cloud and ECE command line interface
    install: |
      bin.install "ecctl"
      system "#{bin}/ecctl", "generate", "completions", "-l", "#{var}/ecctl.auto"
    caveats: |
      If you have previously built ecctl from source, make sure you've removed that binary from any directory that has been added to your user $PATH.
      To enable autocompletion make sure to run `source <(ecctl generate completions)` and add it to your shell interpreter configuration file by running `echo "source <(ecctl generate completions)" >> ~/.bash_profile` or `echo "source <(ecctl generate completions)" >> ~/.zshrc` in case you are using ZSH.
    test: system "#{bin}/ecctl version"
    folder: Formula
builds:
- main: .
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - "386"
  ignore:
    - goos: darwin
      goarch: 386
  ldflags: -s -w -X main.version={{.Env.VERSION }} -X main.commit={{.Commit}} -X main.owner={{.Env.OWNER}} -X main.repo={{.Env.REPO}}
  binary: ecctl
  lang: go
archives:
  - name_template: '{{ .ProjectName }}_{{ .Env.VERSION }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
    - LICENSE*
    - README*
    - docs/*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
nfpms:
  - name_template: "{{ .ProjectName }}_{{ .Env.VERSION }}_{{ .Os }}_{{ .Arch }}"
    license: Apache 2.0
    replacements:
      amd64: 64-bit
      "386": 32-bit
    formats:
      - deb
      - rpm
checksum:
  name_template: '{{ .ProjectName }}_{{ .Env.VERSION }}_checksums.txt'
dist: dist