version: 2
project_name: ecctl
before:
  hooks:
    - go mod download
    - go mod tidy
release:
  github:
    owner: elastic
    name: ecctl
  name_template: '{{.Tag}}'
  draft: false
  disable: true
builds:
- main: .
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - "386"
    - arm64
  ignore:
    - goos: darwin
      goarch: "386"
  ldflags: -s -w -X main.version={{.Env.VERSION }} -X main.commit={{.Commit}} -X main.owner={{.Env.OWNER}} -X main.repo={{.Env.REPO}} -X main.built={{.Env.BUILT}}
  binary: ecctl
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
    format: tar.gz
    files:
    - LICENSE*
    - README*
    - docs/*
snapshot:
  version_template: "{{ .Version }}_SNAPSHOT_{{ .ShortCommit }}"
nfpms:
  - file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}64-bit
      {{- else if eq .Arch "386" }}32-bit
      {{- else }}{{ .Arch }}{{ end }}
    license: Apache 2.0
    maintainer: Elastic Cloud
    vendor: Elastic
    description: ecctl is the CLI for the Elasticsearch Service and Elastic Cloud Enterprise APIs.
    homepage: https://www.elastic.co/guide/en/ecctl/current/index.html
    formats:
      - deb
      - rpm
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
