[id="{p}-release-notes-v1.0.0"]
=== Elastic Cloud Control (ecctl) v1.0.0
++++
<titleabbrev>v1.0.0</titleabbrev>
++++

<<{p}-release-notes-v1.0.0-whats-new,What's new>> | <<{p}-release-notes-v1.0.0-bug-fixes,Bug fixes>> | <<{p}-release-notes-v1.0.0-breaking-changes,Breaking changes>> | <<{p}-release-notes-v1.0.0-changelog,Changelog>>

Welcome to the v1.0.0 release of {n}. This version brings new features, some breaking changes, and bug fixes.

Elastic Cloud Control (ecctl) is Elastic’s CLI to manage Elasticsearch Service (ESS) and Elastic Cloud Enterprise (ECE).

Download the release binaries:

[%hardbreaks]
https://download.elastic.co/downloads/ecctl/1.0.0/ecctl_1.0.0_darwin_amd64.tar.gz[ecctl_1.0.0_darwin_amd64.tar.gz]
https://download.elastic.co/downloads/ecctl/1.0.0/ecctl_1.0.0_linux_32-bit.deb[ecctl_1.0.0_linux_32-bit.deb]
https://download.elastic.co/downloads/ecctl/1.0.0/ecctl_1.0.0_linux_32-bit.rpm[ecctl_1.0.0_linux_32-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.0.0/ecctl_1.0.0_linux_386.tar.g[ecctl_1.0.0_linux_386.tar.g]
https://download.elastic.co/downloads/ecctl/1.0.0/ecctl_1.0.0_linux_64-bit.deb[ecctl_1.0.0_linux_64-bit.deb]
https://download.elastic.co/downloads/ecctl/1.0.0/ecctl_1.0.0_linux_64-bit.rpm[ecctl_1.0.0_linux_64-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.0.0/ecctl_1.0.0_linux_amd64.tar.gz[ecctl_1.0.0_linux_amd64.tar.gz]

[float]
[id="{p}-release-notes-v1.0.0-whats-new"]
==== What's new

* *Deployment create command now supports flag-based actions.* Instance definition flags for the `ecctl deployment create` command are now available. Using a predefined deployment definition JSON file is still optional with the `--file` flag.

* *Enterprise Search support* All relevant commands now support Enterprise Search as a resource kind.
+
[source,sh]
--
$ ecctl deployment plan cancel --kind enterprise_search
--

* *New Elasticsearch keystore commands.* The following commands have been added:
+
--
`ecctl deployment elasticsearch keystore show`:: Shows the settings from the Elasticsearch resource keystore.
`ecctl deployment elasticsearch keystore update`:: Updates the contents of an Elasticsearch resource keystore.
--

* *New User-Agent header.* API calls made through ecctl now use `ecctl/<version>` instead of `cloud-sdk-go/<version>`.

* *Command-layer testing* It is now possible to write tests for commands using the new `testutils.RunCmdAssertion()` testing function:
+
[source,go]
--
func Test_showCmd(t *testing.T) {
<...>
        {
        	name: "succeeds with JSON format",
        	args: testutils.Args{
        		Cmd: showCmd,
        		Args: []string{
        			"show", util.ValidClusterID, "--ref-id=main-elasticsearch",
        		},
        		Cfg: testutils.MockCfg{
        			OutputFormat: "json",
        			Responses: []mock.Response{
        				mock.New200ResponseAssertion(
        					reqAssertion, mock.NewByteBody(showRawResp),
        				),
        			},
        		},
        	},
        	want: testutils.Assertion{
        		Stdout: string(showJSONOutput) + "\n",
        	},
        },
    <...>
    for _, tt := range tests {
    		t.Run(tt.name, func(t *testing.T) {
    			testutils.RunCmdAssertion(t, tt.args, tt.want)
    		})
    	}
--

[float]
[id="{p}-release-notes-v1.0.0-bug-fixes"]
==== Bug fixes

* *Inability to create or update deployments through Ansible.* ecctl should behave in the same manner when executed from the terminal or any automation tool. A bug which showed `os.Stdin` as always populated when coupled with Ansible has been fixed.

* *Allocator vacate flag parsing has been fixed* The `--target` flag was being ignored due to using `GetStringSlice()` when the flag declaration is `Array`. Flag parsing for allocator vacate operations now works as documented.*

[float]
[id="{p}-release-notes-v1.0.0-breaking-changes"]
==== Breaking changes

* *All APIs have been removed.* The APIs that ecctl consumes are useful to other projects. These have now been moved to cloud-sdk-go. If you have any code consuming these APIs, make sure to import the packages from https://github.com/elastic/cloud-sdk-go/tree/master/pkg/api[cloud-sdk-go/pkg/api] instead.

* *Changes with commands and subcommands.* In order to maintain feature parity with the Elastic Cloud API endpoints, the following commands have changed:
+
--
* `ecctl platform stack` is now `ecctl stack`.
* `ecctl platform deployment-template` is now `ecctl deployment template`.
--


[float]
[id="{p}-release-notes-v1.0.0-changelog"]
==== Changelog
// The following section is autogenerated via git

[%hardbreaks]
https://github.com/elastic/ecctl/commit/b86710c[b86710c] build(deps): bump github.com/go-openapi/runtime from 0.19.19 to 0.19.20 (https://github.com/elastic/ecctl/pull/345[#345])
https://github.com/elastic/ecctl/commit/42ce7af[42ce7af] docs: Update to reflect the current state of the project (https://github.com/elastic/ecctl/pull/347[#347])
https://github.com/elastic/ecctl/commit/500e04a[500e04a] allocator: Fix Array parsing to slice parsing (https://github.com/elastic/ecctl/pull/346[#346])
https://github.com/elastic/ecctl/commit/1e9d805[1e9d805] deployment: Add elasticsearch keystore commands (https://github.com/elastic/ecctl/pull/344[#344])
https://github.com/elastic/ecctl/commit/f5d478e[f5d478e] deployment: Add template v2 and remove platform commands (https://github.com/elastic/ecctl/pull/343[#343])
https://github.com/elastic/ecctl/commit/982db38[982db38] deployment: create flags reenabled and Enterprise Search support (https://github.com/elastic/ecctl/pull/341[#341])
https://github.com/elastic/ecctl/commit/d0ba552[d0ba552] enterprise_search: Support and refactor (https://github.com/elastic/ecctl/pull/342[#342])
https://github.com/elastic/ecctl/commit/1f8bd04[1f8bd04] useragent: Add ecctl/<version> UserAgent header (https://github.com/elastic/ecctl/pull/340[#340])
https://github.com/elastic/ecctl/commit/d90a277[d90a277] docs: Add all vacate kinds to `--kind` flag (https://github.com/elastic/ecctl/pull/339[#339])
https://github.com/elastic/ecctl/commit/162f918[162f918] mod: Update cobra, crypto and Go required verisons (https://github.com/elastic/ecctl/pull/338[#338])
https://github.com/elastic/ecctl/commit/33d2c5c[33d2c5c] cmd: Remove sdkcmdutil.FileOrStdin use (https://github.com/elastic/ecctl/pull/337[#337])
https://github.com/elastic/ecctl/commit/21c5b18[21c5b18] deployment-template: Adds a new --template-format flag to command (https://github.com/elastic/ecctl/pull/332[#332])
https://github.com/elastic/ecctl/commit/bef41cf[bef41cf] cmd: fix testutil.newConfig ignored region (https://github.com/elastic/ecctl/pull/336[#336])
https://github.com/elastic/ecctl/commit/fa7fc09[fa7fc09] instance-configuration: Add region to commands (https://github.com/elastic/ecctl/pull/331[#331])
https://github.com/elastic/ecctl/commit/feb03d0[feb03d0] cmd/util/testutils: Add RunCmdAssertion test function (https://github.com/elastic/ecctl/pull/330[#330])
https://github.com/elastic/ecctl/commit/d64b9fe[d64b9fe] user: remove user api and update with sdk imports (https://github.com/elastic/ecctl/pull/328[#328])
https://github.com/elastic/ecctl/commit/32f8c70[32f8c70] stack: Move stack command and subcommands up one level (https://github.com/elastic/ecctl/pull/329[#329])
https://github.com/elastic/ecctl/commit/404fcfc[404fcfc] stack: Move stack command and subcommands up one level (https://github.com/elastic/ecctl/pull/329[#329])
https://github.com/elastic/ecctl/commit/cbf843f[cbf843f] deployment create: Remove region value on non-ESS (https://github.com/elastic/ecctl/pull/326[#326])
https://github.com/elastic/ecctl/commit/8c635e1[8c635e1] deb: Add missing maintainer vendor and description (https://github.com/elastic/ecctl/pull/323[#323])
https://github.com/elastic/ecctl/commit/e6f2ae0[e6f2ae0] proxy: Populate Region field API calls (https://github.com/elastic/ecctl/pull/321[#321])
https://github.com/elastic/ecctl/commit/d722f45[d722f45] platform: Update info command with region (https://github.com/elastic/ecctl/pull/320[#320])
https://github.com/elastic/ecctl/commit/f67d497[f67d497] proxy filtered-groups: Populate Region field API calls (https://github.com/elastic/ecctl/pull/315[#315])
https://github.com/elastic/ecctl/commit/cf61c87[cf61c87] build(deps): bump github.com/go-openapi/runtime from 0.19.15 to 0.19.19 (https://github.com/elastic/ecctl/pull/314[#314])
https://github.com/elastic/ecctl/commit/374ec52[374ec52] deployment-template: Update commands with region (https://github.com/elastic/ecctl/pull/316[#316])
https://github.com/elastic/ecctl/commit/f09b075[f09b075] role: Populate Region field API calls (https://github.com/elastic/ecctl/pull/309[#309])
https://github.com/elastic/ecctl/commit/4bbcb35[4bbcb35] runner: Populate Region field API calls (https://github.com/elastic/ecctl/pull/308[#308])
https://github.com/elastic/ecctl/commit/1088cdf[1088cdf] enrollment-token: Populate Region field API calls (https://github.com/elastic/ecctl/pull/307[#307])
https://github.com/elastic/ecctl/commit/b555750[b555750] misc: Removes files related to clusters API (https://github.com/elastic/ecctl/pull/311[#311])
https://github.com/elastic/ecctl/commit/3883b55[3883b55] Update vendors
https://github.com/elastic/ecctl/commit/bf35dd0[bf35dd0] allocator: Remove the last hashicorp/go-multierror (https://github.com/elastic/ecctl/pull/306[#306])
https://github.com/elastic/ecctl/commit/acd442f[acd442f] repository: Populate snaprepoapi Region field (https://github.com/elastic/ecctl/pull/304[#304])
https://github.com/elastic/ecctl/commit/4dbbf68[4dbbf68] constructor: Populate constructorapi Region field (https://github.com/elastic/ecctl/pull/305[#305])
https://github.com/elastic/ecctl/commit/8d38d56[8d38d56] stack: Populate stackapi Region field (https://github.com/elastic/ecctl/pull/303[#303])
https://github.com/elastic/ecctl/commit/cc3415a[cc3415a] allocator: Populate allocatorapi Region parameter (https://github.com/elastic/ecctl/pull/302[#302])
https://github.com/elastic/ecctl/commit/ed92f72[ed92f72] api: Removes all platform apis and imports the from cloud-sdk-go (https://github.com/elastic/ecctl/pull/299[#299])
https://github.com/elastic/ecctl/commit/72362f3[72362f3] docs: Add --track flag to the deployment examples (https://github.com/elastic/ecctl/pull/300[#300])
https://github.com/elastic/ecctl/commit/84cc91a[84cc91a] mod: Update vendor to 60b0cbb commit (https://github.com/elastic/ecctl/pull/294[#294])
https://github.com/elastic/ecctl/commit/882a69a[882a69a] release: Fix git config and changelog format (https://github.com/elastic/ecctl/pull/287[#287])
https://github.com/elastic/ecctl/commit/c64d740[c64d740] pkg/deployment: Remove package from ecctl (https://github.com/elastic/ecctl/pull/285[#285])
https://github.com/elastic/ecctl/commit/7c145c9[7c145c9] build(deps): bump github.com/spf13/viper from 1.6.3 to 1.7.0 (https://github.com/elastic/ecctl/pull/286[#286])

_Release date: July 22, 2020_
