[id="{p}-release-notes-v1.0.0-beta3"]
=== Elastic Cloud Control (ecctl) v1.0.0-beta3
++++
<titleabbrev>v1.0.0-beta3</titleabbrev>
++++

<<{p}-release-notes-v1.0.0-beta3-whats-new,What's new>> | <<{p}-release-notes-v1.0.0-beta3-bug-fixes,Bug fixes>> | <<{p}-release-notes-v1.0.0-beta3-breaking-changes,Breaking changes>> | <<{p}-release-notes-v1.0.0-beta3-changelog,Changelog>>

Welcome to the v1.0.0-beta3 release of {n}. This version brings new features, some breaking changes, and bug fixes.

Elastic cloud control (ecctl) is Elastic’s CLI to manage Elasticsearch Service (ESS) and Elastic Cloud Enterprise (ECE). It is now open for a public beta.

Download the release binaries:

[%hardbreaks]
https://download.elastic.co/downloads/ecctl/1.0.0-beta3/ecctl_1.0.0-beta3_darwin_amd64.tar.gz[ecctl_1.0.0-beta3_darwin_amd64.tar.gz]
https://download.elastic.co/downloads/ecctl/1.0.0-beta3/ecctl_1.0.0-beta3_linux_32-bit.deb[ecctl_1.0.0-beta3_linux_32-bit.deb]
https://download.elastic.co/downloads/ecctl/1.0.0-beta3/ecctl_1.0.0-beta3_linux_32-bit.rpm[ecctl_1.0.0-beta3_linux_32-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.0.0-beta3/ecctl_1.0.0-beta3_linux_386.tar.g[ecctl_1.0.0-beta3_linux_386.tar.g]
https://download.elastic.co/downloads/ecctl/1.0.0-beta3/ecctl_1.0.0-beta3_linux_64-bit.deb[ecctl_1.0.0-beta3_linux_64-bit.deb]
https://download.elastic.co/downloads/ecctl/1.0.0-beta3/ecctl_1.0.0-beta3_linux_64-bit.rpm[ecctl_1.0.0-beta3_linux_64-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.0.0-beta3/ecctl_1.0.0-beta3_linux_amd64.tar.gz[ecctl_1.0.0-beta3_linux_amd64.tar.gz]

[float]
[id="{p}-release-notes-v1.0.0-beta3-whats-new"]
==== What's new

* *The `ecctl init` command supports ESS and Elasticsearch Service Private users.* You will see a few new options in the init flow. These include the ability to choose your Elastic Cloud offering, and region if you are an Elasticsearch Service customer.


[float]
[id="{p}-release-notes-v1.0.0-beta3-bug-fixes"]
==== Bug fixes

* *Deployment tracking fixed.* Previously the `--track` flag for any command that targeted the deployments API was broken. We are now using a new deployment tracker which also supports AppSearch.

[float]
[id="{p}-release-notes-v1.0.0-beta3-breaking-changes"]
==== Breaking changes

* *Commands which used the deprecated clusters API have been removed.* Actions performed through these commands are available with their `ecctl deployment` or `ecctl deployment resource` counterparts. The following commands and their subcommands have been removed:
+
--
* `ecctl deployment elasticsearch`
* `ecctl deployment kibana`
* `ecctl deployment apm`
* `ecctl deployment appsearch`
--

* *Deployment create command behavior change.* This command no longer supports overriding JSON template fields with flags.

[float]
[id="{p}-release-notes-v1.0.0-beta3-changelog"]
==== Changelog
// The following section is autogenerated via git

[%hardbreaks]
https://github.com/elastic/ecctl/commit/629d5cf[629d5cf] docs: add references to Elasticsearch Service (https://github.com/elastic/ecctl/pull/267[#267])
https://github.com/elastic/ecctl/commit/316bc36[316bc36] cmd: Show ESS options in init command (https://github.com/elastic/ecctl/pull/268[#268])
https://github.com/elastic/ecctl/commit/0ab9525[0ab9525] cmd: Change --cluster flag to --resource-id  (https://github.com/elastic/ecctl/pull/270[#270])
https://github.com/elastic/ecctl/commit/e6fdaf1[e6fdaf1] deps: Update SDK dependency to v1.0.0-beta3 (https://github.com/elastic/ecctl/pull/269[#269])
https://github.com/elastic/ecctl/commit/f7b3691[f7b3691] misc: Add delivery team as docs codeowner (https://github.com/elastic/ecctl/pull/266[#266])
https://github.com/elastic/ecctl/commit/2eaa827[2eaa827] docs: Remove reference to Ansible and Terraform (https://github.com/elastic/ecctl/pull/264[#264])
https://github.com/elastic/ecctl/commit/3e02129[3e02129] docs: Add Nik and Arianna as CODEOWNERS (https://github.com/elastic/ecctl/pull/263[#263])
https://github.com/elastic/ecctl/commit/03b1a51[03b1a51] build(deps): bump github.com/spf13/viper from 1.6.2 to 1.6.3 (https://github.com/elastic/ecctl/pull/260[#260])
https://github.com/elastic/ecctl/commit/bad99dd[bad99dd] misc: Fix App Search typos (https://github.com/elastic/ecctl/pull/259[#259])
https://github.com/elastic/ecctl/commit/a48a843[a48a843] api: Remove code that is related to clusters API (https://github.com/elastic/ecctl/pull/258[#258])
https://github.com/elastic/ecctl/commit/4cc6cce[4cc6cce] ecctl: Prefix config parsing error (https://github.com/elastic/ecctl/pull/254[#254])
https://github.com/elastic/ecctl/commit/ceee1ba[ceee1ba] docs: update getting-started ascii doc to reflect the project's current status (https://github.com/elastic/ecctl/pull/255[#255])
https://github.com/elastic/ecctl/commit/d2ddcc8[d2ddcc8] cmd: remove "deployment elasticsearch" command and subcommand  (https://github.com/elastic/ecctl/pull/251[#251])
https://github.com/elastic/ecctl/commit/06bf08f[06bf08f] formatter: Remove apm and kibana text templates (https://github.com/elastic/ecctl/pull/250[#250])
https://github.com/elastic/ecctl/commit/3e9e5bf[3e9e5bf] docs: Adds Asciidoc generation to "make docs" (https://github.com/elastic/ecctl/pull/249[#249])
https://github.com/elastic/ecctl/commit/6cc3382[6cc3382] Remove "deployment kibana" command and subcommand (https://github.com/elastic/ecctl/pull/248[#248])
https://github.com/elastic/ecctl/commit/198a13b[198a13b] Fix broken link to docs (https://github.com/elastic/ecctl/pull/246[#246])
https://github.com/elastic/ecctl/commit/7191fd4[7191fd4] docs: Update asciidocs to reflect latest changes (https://github.com/elastic/ecctl/pull/244[#244])
https://github.com/elastic/ecctl/commit/4591847[4591847] cmd: Remove deployment appsearch specific commands (https://github.com/elastic/ecctl/pull/243[#243])
https://github.com/elastic/ecctl/commit/551f5d6[551f5d6] Remove "deployment apm" command and subcommands (https://github.com/elastic/ecctl/pull/241[#241])
https://github.com/elastic/ecctl/commit/3967e94[3967e94] cmd: Add missing NewTrackParams tests (https://github.com/elastic/ecctl/pull/242[#242])
https://github.com/elastic/ecctl/commit/462d397[462d397] deps: revert multierror to 1.0.0 (https://github.com/elastic/ecctl/pull/240[#240])
https://github.com/elastic/ecctl/commit/e216ee5[e216ee5] cmd: Temporarily remove ability to create a flag based deployment (https://github.com/elastic/ecctl/pull/239[#239])
https://github.com/elastic/ecctl/commit/133cfff[133cfff] tracker: Use deployment tracker in all tracking (https://github.com/elastic/ecctl/pull/234[#234])
https://github.com/elastic/ecctl/commit/a8cdffe[a8cdffe] build(deps): bump github.com/hashicorp/go-multierror from 1.0.0 to 1.1.0 (https://github.com/elastic/ecctl/pull/238[#238])
https://github.com/elastic/ecctl/commit/8cddd59[8cddd59] build(deps): bump github.com/go-openapi/runtime from 0.19.14 to 0.19.15 (https://github.com/elastic/ecctl/pull/237[#237])
https://github.com/elastic/ecctl/commit/820fa76[820fa76] docs: remove negative connotation (https://github.com/elastic/ecctl/pull/236[#236])
https://github.com/elastic/ecctl/commit/5903f54[5903f54] build(deps): bump github.com/spf13/cobra from 0.0.6 to 0.0.7 (https://github.com/elastic/ecctl/pull/235[#235])
https://github.com/elastic/ecctl/commit/477efc1[477efc1] cmd: specify that deployment delete command is ECE specific (https://github.com/elastic/ecctl/pull/233[#233])
https://github.com/elastic/ecctl/commit/2bfa679[2bfa679] cmd: specify that deployment template commands are ECE specific (https://github.com/elastic/ecctl/pull/232[#232])
https://github.com/elastic/ecctl/commit/46ad1cd[46ad1cd] cmd: add instance flags to deployment create command (https://github.com/elastic/ecctl/pull/224[#224])
https://github.com/elastic/ecctl/commit/84cf2ce[84cf2ce] misc: change codeowners (https://github.com/elastic/ecctl/pull/227[#227])
https://github.com/elastic/ecctl/commit/b0ca1a9[b0ca1a9] build(deps): bump github.com/go-openapi/runtime from 0.19.12 to 0.19.14 (https://github.com/elastic/ecctl/pull/222[#222])
https://github.com/elastic/ecctl/commit/9d6ab54[9d6ab54] docs: Add brew upgrade instructions (https://github.com/elastic/ecctl/pull/219[#219])
https://github.com/elastic/ecctl/commit/d743d9b[d743d9b] init: Change example command to deployment list (https://github.com/elastic/ecctl/pull/218[#218])
https://github.com/elastic/ecctl/commit/4a73736[4a73736] docs: Modify changelog generator for adoc files (https://github.com/elastic/ecctl/pull/217[#217])
https://github.com/elastic/ecctl/commit/b3f6d85[b3f6d85] Fix GitHub release action (https://github.com/elastic/ecctl/pull/214[#214])
https://github.com/elastic/ecctl/commit/cd57f9f[cd57f9f] Fix small formatting mistake on Release Notes (https://github.com/elastic/ecctl/pull/215[#215])

_Release date: April 30, 2020_
