[id="{p}-release-notes-v1.1.0"]
=== Elastic Cloud Control (ecctl) v1.1.0
++++
<titleabbrev>v1.1.0</titleabbrev>
++++

<<{p}-release-notes-v1.1.0-whats-new,What's new>> | <<{p}-release-notes-v1.1.0-bug-fixes,Bug fixes>> | <<{p}-release-notes-v1.1.0-changelog,Changelog>>

Welcome to the v1.1.0 release of {n}. This version brings new features, some breaking changes, and bug fixes.

Elastic Cloud Control (ecctl) is Elastic’s CLI to manage Elasticsearch Service (ESS) and Elastic Cloud Enterprise (ECE).

Download the release binaries:

[%hardbreaks]
https://download.elastic.co/downloads/ecctl/1.1.0/ecctl_1.1.0_darwin_amd64.tar.gz[ecctl_1.1.0_darwin_amd64.tar.gz]
https://download.elastic.co/downloads/ecctl/1.1.0/ecctl_1.1.0_linux_32-bit.deb[ecctl_1.1.0_linux_32-bit.deb]
https://download.elastic.co/downloads/ecctl/1.1.0/ecctl_1.1.0_linux_32-bit.rpm[ecctl_1.1.0_linux_32-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.1.0/ecctl_1.1.0_linux_386.tar.g[ecctl_1.1.0_linux_386.tar.gz]
https://download.elastic.co/downloads/ecctl/1.1.0/ecctl_1.1.0_linux_64-bit.deb[ecctl_1.1.0_linux_64-bit.deb]
https://download.elastic.co/downloads/ecctl/1.1.0/ecctl_1.1.0_linux_64-bit.rpm[ecctl_1.1.0_linux_64-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.1.0/ecctl_1.1.0_linux_amd64.tar.gz[ecctl_1.1.0_linux_amd64.tar.gz]

[float]
[id="{p}-release-notes-v1.1.0-whats-new"]
==== What's new

* *Authorization headers are now redacted when using `--verbose`.* The default behavior of the `--verbose` flag has been changed to redact the contents of the Authorization header in outgoing http requests. To disable this behavior, set `--verbose-credentials` or `verbose_credentials: true` in the configuration file.

* *New global flags.* Two new flags have been added:
+
--
`ecctl --verbose-credentials`:: When set, Authorization headers on the request/response trail will be displayed as plain text.
`ecctl --verbose-file <string>`:: When set, the verbose request/response trail will be written to the defined file.
--

* *New configuration options.* Two new configuration options have been added:
+
--
`verbose_credentials (bool)`:: When set, Authorization headers on the request/response trail will be displayed as plain text.
`verbose_file (string)`:: When set, the verbose request/response trail will be written to the defined file.
--


* *Allocator list command now supports a `--size` flag.* With the addition of the new flag, users are able to obtain more than the default per region allocator limit of 100.

* *New Platform role command.* One new command has been added:
+
--
`ecctl platform role update`:: Updates an existing platform role from a file definition.
--

[float]
[id="{p}-release-notes-v1.1.0-bug-fixes"]
==== Bug fixes

* *Allocator list `--all` flag description has been amended.* Changed the vague flag description to reflect that the flag is still bound to the size limit defined in the `--size` flag.

* *Deployment show `--generate-update-payload` flag output has been amended.* Fixed a bug where the observability settings were not included in the generated payload.

[float]
[id="{p}-release-notes-v1.1.0-changelog"]
==== Changelog
// The following section is autogenerated via git

[%hardbreaks]
https://github.com/elastic/ecctl/commit/7fffe36[7fffe36] deps: Update cloud-sdk-go to latest commit (https://github.com/elastic/ecctl/pull/409[#409])
https://github.com/elastic/ecctl/commit/6c6e7b0[6c6e7b0] release: Adds changelog for 1.1.0 release (https://github.com/elastic/ecctl/pull/406[#406])
https://github.com/elastic/ecctl/commit/d0be241[d0be241] cmd: Add new verbose configuration flags (https://github.com/elastic/ecctl/pull/405[#405])
https://github.com/elastic/ecctl/commit/6ebe5cf[6ebe5cf] mod: Update elastic/cloud-sdk-go to v1.1.0 (https://github.com/elastic/ecctl/pull/404[#404])
https://github.com/elastic/ecctl/commit/bef0650[bef0650] mod: Update cloud-sdk-go to 6fc0976 (https://github.com/elastic/ecctl/pull/400[#400])
https://github.com/elastic/ecctl/commit/29d28de[29d28de] release: (1.0) Add hub.protocol https to script (https://github.com/elastic/ecctl/pull/399[#399])
https://github.com/elastic/ecctl/commit/84b0ee8[84b0ee8] add update role command (https://github.com/elastic/ecctl/pull/392[#392])
https://github.com/elastic/ecctl/commit/8d5cac1[8d5cac1] mod: bump sdk version to fc4e5b0 commit hash (https://github.com/elastic/ecctl/pull/393[#393])
https://github.com/elastic/ecctl/commit/e247bdf[e247bdf] docs: Fix link (https://github.com/elastic/ecctl/pull/388[#388])
https://github.com/elastic/ecctl/commit/10f65d0[10f65d0] docs: Fix links  (https://github.com/elastic/ecctl/pull/385[#385])
https://github.com/elastic/ecctl/commit/9f01b34[9f01b34] Correct bad cross-product links (https://github.com/elastic/ecctl/pull/384[#384])
https://github.com/elastic/ecctl/commit/0646c72[0646c72] fix: ignored EC_API_KEY environment variable (https://github.com/elastic/ecctl/pull/379[#379])
https://github.com/elastic/ecctl/commit/baf7e44[baf7e44] go: Update to go 1.15 (https://github.com/elastic/ecctl/pull/380[#380])
https://github.com/elastic/ecctl/commit/41d6058[41d6058] allocator: Amend --all flag description (https://github.com/elastic/ecctl/pull/378[#378])
https://github.com/elastic/ecctl/commit/7e0a59b[7e0a59b] allocator: Add --size flag to list command (https://github.com/elastic/ecctl/pull/375[#375])
https://github.com/elastic/ecctl/commit/eed17e8[eed17e8] deps: Enable renovate and update (https://github.com/elastic/ecctl/pull/372[#372])
https://github.com/elastic/ecctl/commit/180a5fa[180a5fa] release: Fix git commit by adding user and email (https://github.com/elastic/ecctl/pull/366[#366])
https://github.com/elastic/ecctl/commit/45299ba[45299ba] docs: Add asciidoc document validator in make docs (https://github.com/elastic/ecctl/pull/369[#369])
https://github.com/elastic/ecctl/commit/22e8e24[22e8e24] version: Bump master branch to v1.1.0 (https://github.com/elastic/ecctl/pull/368[#368])
https://github.com/elastic/ecctl/commit/84593d3[84593d3] release: Fix changelog generator broken link (https://github.com/elastic/ecctl/pull/367[#367])
https://github.com/elastic/ecctl/commit/9f33b6f[9f33b6f] docs: Remove duplicated synopsis from doc files (https://github.com/elastic/ecctl/pull/370[#370])
https://github.com/elastic/ecctl/commit/eb54811[eb54811] docs: remove asciidoc beta disclaimer (https://github.com/elastic/ecctl/pull/365[#365])

_Release date: December 3, 2020_
