[id="{p}-release-notes-v1.14.0"]
=== Elastic Cloud Control (ecctl) v1.14.0
++++
<titleabbrev>v1.14.0</titleabbrev>
++++

<<{p}-release-notes-v1.14.0-whats-new,What's new>> | <<{p}-release-notes-v1.14.0-bug-fixes,Bug fixes>> | <<{p}-release-notes-v1.14.0-breaking-changes,Breaking changes>> | <<{p}-release-notes-v1.14.0-changelog,Changelog>>

Welcome to the v1.14.0 release of {n}. This version brings new features, some breaking changes, and bug fixes.

Elastic Cloud Control (ecctl) is Elastic’s CLI to manage Elasticsearch Service (ESS) and Elastic Cloud Enterprise (ECE).

Download the release binaries:

[%hardbreaks]
https://download.elastic.co/downloads/ecctl/1.14.0/ecctl_1.14.0_darwin_amd64.tar.gz[ecctl_1.14.0_darwin_amd64.tar.gz]
https://download.elastic.co/downloads/ecctl/1.14.0/ecctl_1.14.0_linux_32-bit.deb[ecctl_1.14.0_linux_32-bit.deb]
https://download.elastic.co/downloads/ecctl/1.14.0/ecctl_1.14.0_linux_32-bit.rpm[ecctl_1.14.0_linux_32-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.14.0/ecctl_1.14.0_linux_386.tar.gz[ecctl_1.14.0_linux_386.tar.gz]
https://download.elastic.co/downloads/ecctl/1.14.0/ecctl_1.14.0_linux_64-bit.deb[ecctl_1.14.0_linux_64-bit.deb]
https://download.elastic.co/downloads/ecctl/1.14.0/ecctl_1.14.0_linux_64-bit.rpm[ecctl_1.14.0_linux_64-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.14.0/ecctl_1.14.0_linux_amd64.tar.gz[ecctl_1.14.0_linux_amd64.tar.gz]

[float]
[id="{p}-release-notes-v1.14.0-whats-new"]
==== What's new

* *Deployment search: Add flag to return all matches. (https://github.com/elastic/ecctl/pull/664[#664]):*
By default, the `deployment search` command just executes one query and returns the results. The command now also supports the `--all-matches` flag to query and return larger number of results that would exceed the maximum size of a single request.

[float]
[id="{p}-release-notes-v1.14.0-bug-fixes"]
==== Bug fixes

* *Clear transients update plan (https://github.com/elastic/ecctl/pull/649[#649]):*
The update payload generated with `--generate-update-payload` used to include transient fields from the latest plan. These are now not included anymore by default.


[float]
[id="{p}-release-notes-v1.14.0-changelog"]
==== Changelog
// The following section is autogenerated via git

[%hardbreaks]
https://github.com/elastic/ecctl/commit/f2fc756[f2fc756] Deployment search: Add flag to return all matches. (https://github.com/elastic/ecctl/pull/664[#664])
https://github.com/elastic/ecctl/commit/0b631c8[0b631c8] fix(deps): update module golang.org/x/term to v0.22.0 (https://github.com/elastic/ecctl/pull/657[#657])
https://github.com/elastic/ecctl/commit/92d35ea[92d35ea] [Chore]: Update the URL fragment for API keys (https://github.com/elastic/ecctl/pull/658[#658])
https://github.com/elastic/ecctl/commit/eaefc6b[eaefc6b] fix(deps): update module github.com/elastic/cloud-sdk-go to v1.20.0 (https://github.com/elastic/ecctl/pull/656[#656])
https://github.com/elastic/ecctl/commit/fd54678[fd54678] fix(deps): update module github.com/spf13/cobra to v1.8.1 (https://github.com/elastic/ecctl/pull/655[#655])
https://github.com/elastic/ecctl/commit/81cceca[81cceca] fix(deps): update module github.com/spf13/viper to v1.19.0 (https://github.com/elastic/ecctl/pull/652[#652])
https://github.com/elastic/ecctl/commit/c9e706f[c9e706f] chore(deps): update goreleaser/goreleaser-action action to v6 (https://github.com/elastic/ecctl/pull/654[#654])
https://github.com/elastic/ecctl/commit/3584bdf[3584bdf] fix(deps): update module golang.org/x/term to v0.21.0 (https://github.com/elastic/ecctl/pull/653[#653])
https://github.com/elastic/ecctl/commit/c47b9d5[c47b9d5] Expose clear_transients in ecctl (https://github.com/elastic/ecctl/pull/649[#649])
https://github.com/elastic/ecctl/commit/54341aa[54341aa] fix(deps): update module golang.org/x/term to v0.20.0 (https://github.com/elastic/ecctl/pull/647[#647])
https://github.com/elastic/ecctl/commit/96e6e1e[96e6e1e] fix(deps): update module github.com/elastic/cloud-sdk-go to v1.18.0 (https://github.com/elastic/ecctl/pull/648[#648])
https://github.com/elastic/ecctl/commit/0ff35de[0ff35de] chore(deps): update actions/cache action to v4 (https://github.com/elastic/ecctl/pull/640[#640])
https://github.com/elastic/ecctl/commit/e23d71e[e23d71e] chore(deps): update actions/checkout action to v4 (https://github.com/elastic/ecctl/pull/618[#618])
https://github.com/elastic/ecctl/commit/e332de9[e332de9] fix(deps): update module github.com/asaskevich/govalidator to v0.0.0-20230301143203-a9d515a09cc2 (https://github.com/elastic/ecctl/pull/646[#646])
https://github.com/elastic/ecctl/commit/54cfae1[54cfae1] chore(deps): update actions/setup-go action to v5 (https://github.com/elastic/ecctl/pull/632[#632])
https://github.com/elastic/ecctl/commit/a5cc331[a5cc331] fix(deps): update module golang.org/x/term to v0.19.0 (https://github.com/elastic/ecctl/pull/642[#642])

_Release date: September 26, 2024_
