[id="{p}-release-notes-v1.3.0"]
=== Elastic Cloud Control (ecctl) v1.3.0
++++
<titleabbrev>v1.3.0</titleabbrev>
++++

<<{p}-release-notes-v1.3.0-whats-new,What's new>> | <<{p}-release-notes-v1.3.0-bug-fixes,Bug fixes>> | <<{p}-release-notes-v1.3.0-breaking-changes,Breaking changes>> | <<{p}-release-notes-v1.3.0-changelog,Changelog>>

Welcome to the v1.3.0 release of {n}. This version brings new features, some breaking changes, and bug fixes.

Elastic Cloud Control (ecctl) is Elastic’s CLI to manage Elasticsearch Service (ESS) and Elastic Cloud Enterprise (ECE).

Download the release binaries:

[%hardbreaks]
https://download.elastic.co/downloads/ecctl/1.3.0/ecctl_1.3.0_darwin_amd64.tar.gz[ecctl_1.3.0_darwin_amd64.tar.gz]
https://download.elastic.co/downloads/ecctl/1.3.0/ecctl_1.3.0_linux_32-bit.deb[ecctl_1.3.0_linux_32-bit.deb]
https://download.elastic.co/downloads/ecctl/1.3.0/ecctl_1.3.0_linux_32-bit.rpm[ecctl_1.3.0_linux_32-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.3.0/ecctl_1.3.0_linux_386.tar.g[ecctl_1.3.0_linux_386.tar.gz]
https://download.elastic.co/downloads/ecctl/1.3.0/ecctl_1.3.0_linux_64-bit.deb[ecctl_1.3.0_linux_64-bit.deb]
https://download.elastic.co/downloads/ecctl/1.3.0/ecctl_1.3.0_linux_64-bit.rpm[ecctl_1.3.0_linux_64-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.3.0/ecctl_1.3.0_linux_amd64.tar.gz[ecctl_1.3.0_linux_amd64.tar.gz]

[float]
[id="{p}-release-notes-v1.3.0-whats-new"]
==== What's new

* *New top level command: `ecctl comment`.* Includes commands to create, delete, list, show and update comments for any of the Elastic Cloud resources: `elasticsearch`, `kibana`, `apm`, `appsearch`, `enterprise_search`, `allocator`, `constructor`, `runner`, `proxy`.

* *New deployment command: `ecctl deployment traffic-filter`.* Includes commands to create, delete, list and show traffic filter rules and the `ecctl deployment traffic-filter association` sub-command includes two more sub-commands to create and delete associations between traffic rules and deployments.

* *New deployment command: `ecctl deployment extension`.* Includes commands to create, delete list and show custom deployment extensions such as Elasticsearch bundles or plugins.

* *Added support for data tiers in all `ecctl deployment` commands.*

[float]
[id="{p}-release-notes-v1.3.0-bug-fixes"]
==== Bug fixes

* *Improved deployment tracking.* The deployment tracking has been improved. It now fails only when the plan completes with a failure, instead of returning errors from other steps of the plan.

[float]
[id="{p}-release-notes-v1.3.0-breaking-changes"]
==== Breaking changes

* *Deployment create drops support flag-based actions.* Instance definition flags for the `ecctl deployment create` command have been removed. Using a predefined deployment definition JSON file is still optional with the `--file` flag, and the `--deployment-template` flag can be used to create a deployment from a template using the template configuration. See `ecctl deployment create --help` for a full list of examples.

[float]
[id="{p}-release-notes-v1.3.0-changelog"]
==== Changelog
// The following section is autogenerated via git

[%hardbreaks]
https://github.com/elastic/ecctl/commit/e7588f0[e7588f0] deployment: New extension create subcommand (https://github.com/elastic/ecctl/pull/470[#470])
https://github.com/elastic/ecctl/commit/968729d[968729d] traffic-filter: Associations create and delete subcommands (https://github.com/elastic/ecctl/pull/468[#468])
https://github.com/elastic/ecctl/commit/d5f8b99[d5f8b99] traffic-filter: Adds create command (https://github.com/elastic/ecctl/pull/463[#463])
https://github.com/elastic/ecctl/commit/19a080d[19a080d] traffic-filter: Fix deleteCmd test (https://github.com/elastic/ecctl/pull/469[#469])
https://github.com/elastic/ecctl/commit/c7041e7[c7041e7] deployment command: Remove flag based create (https://github.com/elastic/ecctl/pull/460[#460])
https://github.com/elastic/ecctl/commit/54cd667[54cd667] comment: Adjust text to specify the command is ECE only (https://github.com/elastic/ecctl/pull/462[#462])
https://github.com/elastic/ecctl/commit/e5d22b5[e5d22b5] deployment: Adds read and delete extension subcommands (https://github.com/elastic/ecctl/pull/458[#458])
https://github.com/elastic/ecctl/commit/6a9e3e9[6a9e3e9] implements comment show command (https://github.com/elastic/ecctl/pull/461[#461])
https://github.com/elastic/ecctl/commit/bf049ac[bf049ac] Implement comment delete command (https://github.com/elastic/ecctl/pull/466[#466])
https://github.com/elastic/ecctl/commit/882c0b0[882c0b0] implements comment update command (https://github.com/elastic/ecctl/pull/467[#467])
https://github.com/elastic/ecctl/commit/44509f5[44509f5] implements comment list command (https://github.com/elastic/ecctl/pull/464[#464])
https://github.com/elastic/ecctl/commit/86d353a[86d353a] alings create comment command texts (https://github.com/elastic/ecctl/pull/465[#465])
https://github.com/elastic/ecctl/commit/bb3ddfb[bb3ddfb] gh issues: Update bug issue template (https://github.com/elastic/ecctl/pull/457[#457])
https://github.com/elastic/ecctl/commit/4603cf3[4603cf3] implement comment create command (https://github.com/elastic/ecctl/pull/459[#459])
https://github.com/elastic/ecctl/commit/73c3e03[73c3e03] deployment: New commands for traffic-filter show, list and delete (https://github.com/elastic/ecctl/pull/455[#455])
https://github.com/elastic/ecctl/commit/7680eff[7680eff] mod: Update sdk to fix plan tracker bugs (https://github.com/elastic/ecctl/pull/454[#454])
https://github.com/elastic/ecctl/commit/8721b65[8721b65] mod: Update cloud-sdk-go to post swagger update (https://github.com/elastic/ecctl/pull/453[#453])
https://github.com/elastic/ecctl/commit/a9634b6[a9634b6] mod: Updates SDK to ECE 2.9.0 spec (https://github.com/elastic/ecctl/pull/450[#450])
https://github.com/elastic/ecctl/commit/911a7ea[911a7ea] docs: Set deployment node command as ECE only (https://github.com/elastic/ecctl/pull/446[#446])
https://github.com/elastic/ecctl/commit/c3dc300[c3dc300] Fix 1.2.0 release notes not building for docs/pull/2059 (https://github.com/elastic/ecctl/pull/444[#444])
https://github.com/elastic/ecctl/commit/c3742ee[c3742ee] build: Fix release GH action (https://github.com/elastic/ecctl/pull/443[#443])
https://github.com/elastic/ecctl/commit/29b1fbd[29b1fbd] fixup: release notes (https://github.com/elastic/ecctl/pull/442[#442])
https://github.com/elastic/ecctl/commit/fd52a87[fd52a87] docs: Improved release documentation (https://github.com/elastic/ecctl/pull/440[#440])

_Release date: March 23, 2021_
