[id="{p}-release-notes-v1.9.0"]
=== Elastic Cloud Control (ecctl) v1.9.0
++++
<titleabbrev>v1.9.0</titleabbrev>
++++

<<{p}-release-notes-v1.9.0-whats-new,What's new>> | <<{p}-release-notes-v1.9.0-bug-fixes,Bug fixes>> |  <<{p}-release-notes-v1.9.0-changelog,Changelog>>

Welcome to the v1.9.0 release of {n}. This version brings new features, some breaking changes, and bug fixes.

Elastic Cloud Control (ecctl) is Elastic’s CLI to manage Elasticsearch Service (ESS) and Elastic Cloud Enterprise (ECE).

Download the release binaries:

[%hardbreaks]
https://download.elastic.co/downloads/ecctl/1.9.0/ecctl_1.9.0_darwin_amd64.tar.gz[ecctl_1.9.0_darwin_amd64.tar.gz]
https://download.elastic.co/downloads/ecctl/1.9.0/ecctl_1.9.0_linux_32-bit.deb[ecctl_1.9.0_linux_32-bit.deb]
https://download.elastic.co/downloads/ecctl/1.9.0/ecctl_1.9.0_linux_32-bit.rpm[ecctl_1.9.0_linux_32-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.9.0/ecctl_1.9.0_linux_386.tar.gz[ecctl_1.9.0_linux_386.tar.gz]
https://download.elastic.co/downloads/ecctl/1.9.0/ecctl_1.9.0_linux_64-bit.deb[ecctl_1.9.0_linux_64-bit.deb]
https://download.elastic.co/downloads/ecctl/1.9.0/ecctl_1.9.0_linux_64-bit.rpm[ecctl_1.9.0_linux_64-bit.rpm]
https://download.elastic.co/downloads/ecctl/1.9.0/ecctl_1.9.0_linux_amd64.tar.gz[ecctl_1.9.0_linux_amd64.tar.gz]

[float]
[id="{p}-release-notes-v1.9.0-whats-new"]
==== What's new

* *`Update elastic/cloud-sdk-go` to `v1.11.0`*. Includes all the new API changes for ECE `3.4.0`.
* Various dependencies have been updated to their latest version.

[float]
[id="{p}-release-notes-v1.9.0-bug-fixes"]
==== Bug fixes

* *Deployment show `--generate-update-payload` flag fixed.* There was an issue where the generated payload would not validate if autoscaling is enabled. (https://github.com/elastic/ecctl/issues/596[#596])
* *Fixed manual confirmation for some commands* The confirmation dialog for some commands was not working, so commands had to be called using the `--force` flag. The confirmation dialogs now work properly. (https://github.com/elastic/ecctl/issues/560[#560])

[float]
[id="{p}-release-notes-v1.9.0-changelog"]
==== Changelog
// The following section is autogenerated via git

[%hardbreaks]
https://github.com/elastic/ecctl/commit/b6836f3[b6836f3] Correct arguments on ConfirmAction() (https://github.com/elastic/ecctl/pull/561[#561])
https://github.com/elastic/ecctl/commit/d704fcc[d704fcc] chore(deps): update module go to 1.19 (https://github.com/elastic/ecctl/pull/580[#580])
https://github.com/elastic/ecctl/commit/efe9b87[efe9b87] Update cloud-sdk-go to 1.11.0. (https://github.com/elastic/ecctl/pull/598[#598])
https://github.com/elastic/ecctl/commit/35ebdc7[35ebdc7] fix(deps): update module github.com/spf13/viper to v1.14.0 (https://github.com/elastic/ecctl/pull/591[#591])
https://github.com/elastic/ecctl/commit/b83363d[b83363d] fix(deps): update module golang.org/x/term to v0.1.0 (https://github.com/elastic/ecctl/pull/589[#589])
https://github.com/elastic/ecctl/commit/54d0f1e[54d0f1e] chore(deps): update goreleaser/goreleaser-action action to v3 (https://github.com/elastic/ecctl/pull/572[#572])
https://github.com/elastic/ecctl/commit/9f5565f[9f5565f] fix(deps): update module github.com/stretchr/testify to v1.8.1 (https://github.com/elastic/ecctl/pull/590[#590])
https://github.com/elastic/ecctl/commit/901cc82[901cc82] fix(deps): update module github.com/elastic/cloud-sdk-go to v1.10.0 (https://github.com/elastic/ecctl/pull/581[#581])
https://github.com/elastic/ecctl/commit/5780a9b[5780a9b] fix(deps): update golang.org/x/term digest to 7a66f97 (https://github.com/elastic/ecctl/pull/585[#585])
https://github.com/elastic/ecctl/commit/cf20565[cf20565] fix(deps): update module github.com/spf13/viper to v1.13.0 (https://github.com/elastic/ecctl/pull/583[#583])
https://github.com/elastic/ecctl/commit/1fe5d42[1fe5d42] fix(deps): update module github.com/spf13/cobra to v1.5.0 (https://github.com/elastic/ecctl/pull/577[#577])
https://github.com/elastic/ecctl/commit/f582ee7[f582ee7] fix(deps): update golang.org/x/term digest to a9ba230 (https://github.com/elastic/ecctl/pull/579[#579])
https://github.com/elastic/ecctl/commit/52a2f3a[52a2f3a] fix(deps): update module github.com/stretchr/testify to v1.8.0 (https://github.com/elastic/ecctl/pull/576[#576])
https://github.com/elastic/ecctl/commit/1f1c944[1f1c944] fix(deps): update module github.com/spf13/viper to v1.12.0 (https://github.com/elastic/ecctl/pull/575[#575])
https://github.com/elastic/ecctl/commit/79c2650[79c2650] fix(deps): update golang.org/x/term digest to 065cf7b (https://github.com/elastic/ecctl/pull/574[#574])
https://github.com/elastic/ecctl/commit/0dda8e4[0dda8e4] fix(deps): update module github.com/elastic/cloud-sdk-go to v1.9.0 (https://github.com/elastic/ecctl/pull/571[#571])
https://github.com/elastic/ecctl/commit/8e8aa93[8e8aa93] fix(deps): update golang.org/x/term digest to e5f449a (https://github.com/elastic/ecctl/pull/569[#569])
https://github.com/elastic/ecctl/commit/753bfec[753bfec] fix(deps): update module github.com/spf13/viper to v1.11.0 (https://github.com/elastic/ecctl/pull/570[#570])
https://github.com/elastic/ecctl/commit/3cfc244[3cfc244] chore(deps): update peterjgrainger/action-create-branch action to v2.2.0 (https://github.com/elastic/ecctl/pull/568[#568])
https://github.com/elastic/ecctl/commit/381ee81[381ee81] chore(deps): update actions/cache action to v3 (https://github.com/elastic/ecctl/pull/567[#567])
https://github.com/elastic/ecctl/commit/a1817ef[a1817ef] fix(deps): update module github.com/elastic/cloud-sdk-go to v1.8.1 (https://github.com/elastic/ecctl/pull/558[#558])
https://github.com/elastic/ecctl/commit/63220f4[63220f4] chore(deps): update actions/setup-go action to v3 (https://github.com/elastic/ecctl/pull/562[#562])
https://github.com/elastic/ecctl/commit/b6888cc[b6888cc] chore(deps): update actions/checkout action to v3 (https://github.com/elastic/ecctl/pull/563[#563])
https://github.com/elastic/ecctl/commit/66cda92[66cda92] fix(deps): update module github.com/spf13/cobra to v1.4.0 (https://github.com/elastic/ecctl/pull/564[#564])
https://github.com/elastic/ecctl/commit/0669bf7[0669bf7] chore(deps): update endbug/add-and-commit action to v9 (https://github.com/elastic/ecctl/pull/565[#565])
https://github.com/elastic/ecctl/commit/fea9edf[fea9edf] fix(deps): update module github.com/stretchr/testify to v1.7.1 (https://github.com/elastic/ecctl/pull/566[#566])
https://github.com/elastic/ecctl/commit/1d74b59[1d74b59] Update CODEOWNERS (https://github.com/elastic/ecctl/pull/557[#557])
https://github.com/elastic/ecctl/commit/5eac3e1[5eac3e1] Adjust CODEOWNERS (https://github.com/elastic/ecctl/pull/556[#556])
https://github.com/elastic/ecctl/commit/f3661bd[f3661bd] Update minor version

_Release date: December 02, 2022_
