#!/bin/bash

KRAMDOC_DOCKER_IMAGE=asciidoctor/docker-asciidoctor

# Delete the docs
echo "-> Deleting docs..."
rm -f docs/*.md
# Delete only the autogenerated markdown config, skipping the manually created docs.
rm -f docs/ecctl_*.adoc


echo "-> Regenerating Markdown..."
go run main.go generate docs


echo "-> Regenerating Asciidoc..."
cd docs

# Convert the Markdown files to Asciidoctor
docker run --rm -v $(pwd):/documents ${KRAMDOC_DOCKER_IMAGE} find ./ -name "*.md" -type f -exec sh -c 'kramdoc {}' \;

# Add the section IDs required for links
for file in ecctl*.adoc; do 
    echo "[#$file]"$'\n'"$(cat -- "$file")" > "$file"
done

# Strip extraneous .adoc out of section IDs and xrefs
sed -i '' -e 's/\.adoc//g' ecctl*.adoc

# Add [float] tags to H3 sections to keep content together
sed -i '' -e 's/===/\[float]\
&/g' ecctl*.adoc

# Generate the index file for imbedding the command reference content and sort it
for file in ecctl*.adoc; do
    if [[ $file != "ecctl-command-reference-index.adoc" ]]; then
        echo "include::$file[]" >> "temp-index.adoc"
    fi
done
sort temp-index.adoc > ecctl-command-reference-index.adoc; rm temp-index.adoc