#!/bin/bash

set -e

KRAMDOC_DOCKER_IMAGE=asciidoctor/docker-asciidoctor

# Delete the docs
echo "-> Deleting docs..."
rm -f docs/*.md
# Delete only the autogenerated markdown config, skipping the manually created docs.
rm -f docs/ecctl_*.adoc


echo "-> Regenerating Markdown..."
go run main.go generate docs


echo "-> Regenerating Asciidoc..."

# Convert the Markdown files to Asciidoctor
DOCS_VOL=$(docker volume create docs-vol)
DOCS_HELPER=$(docker create -v ${DOCS_VOL}:/documents alpine true)
docker cp $(pwd)/docs ${DOCS_HELPER}:/documents/docs
docker run --rm -v ${DOCS_VOL}:/documents ${KRAMDOC_DOCKER_IMAGE} find ./ -name "*.md" -type f -exec sh -c 'kramdoc {}' \;
docker cp ${DOCS_HELPER}:/documents/docs $(pwd)
docker rm ${DOCS_HELPER}
docker volume rm ${DOCS_VOL}

cd docs
if [[ ! -z ${GITHUB_ACTIONS} ]]; then
    sudo chown -R $(id -u):$(id -g) .
fi

# Add the section IDs required for links
for file in ecctl*.adoc; do 
    echo "[#$file]"$'\n'"$(cat -- "$file")" > "$file"
done

# Strip extraneous .adoc out of section IDs and xrefs
sed -i'.bak' -e 's/\.adoc//g' ecctl*.adoc

# Replace ECE availability text for ece icon
sed -i'.bak' -e 's/(Available for ECE only)/{ece-icon} (Available for ECE only)/g' ecctl*.adoc

# Add [float] tags to H3 sections to keep content together
sed -i'.bak' -e 's/===/\[float]\
&/g' ecctl*.adoc

rm -f *.bak

# Generate the index file for imbedding the command reference content and sort it
for file in ecctl*.adoc; do
    if [[ $file != "ecctl-command-reference-index.adoc" ]]; then
        echo "include::$file[]" >> "temp-index.adoc"
    fi
done
sort temp-index.adoc > ecctl-command-reference-index.adoc; rm temp-index.adoc

echo "-> Validating ASCIIDOC files..."

# Creating /shared/attributes.asciidoc is necessary since it's part of our
# common doc build process, and the file is imported in docs/index.asciidoc.
docker run -v $(pwd):/documents/ asciidoctor/docker-asciidoctor bash -c '
shopt -s extglob
mkdir -p /shared && touch /shared/attributes.asciidoc
asciidoctor --failure-level ERROR -o /dev/null ?(*.adoc|*.asciidoc)'
