[#ecctl_platform_instance-configuration]
== ecctl platform instance-configuration

Manages instance configurations (Available for ECE only)

[float]
=== Synopsis

Manages instance configurations (Available for ECE only)

----
ecctl platform instance-configuration [flags]
----

[float]
=== Options

----
  -h, --help   help for instance-configuration
----

[float]
=== Options inherited from parent commands

----
      --apikey string      API key to use to authenticate (If empty will look for EC_APIKEY environment variable)
      --config string      Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force              Do not ask for confirmation
      --format string      Formats the output using a Go template
      --host string        Base URL to use
      --insecure           Skips all TLS validation
      --message string     A message to set on cluster operation
      --output string      Output format [text|json] (default "text")
      --pass string        Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof              Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet              Suppresses the configuration file used for the run, if any
      --region string      Elasticsearch Service region
      --timeout duration   Timeout to use on all HTTP calls (default 30s)
      --trace              Enables tracing saves the trace to trace-20060102150405
      --user string        Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose            Enable verbose mode
----

[float]
=== SEE ALSO

* xref:ecctl_platform[ecctl platform]	 - Manages the platform (Available for ECE only)
* xref:ecctl_platform_instance-configuration_create[ecctl platform instance-configuration create]	 - Creates a new instance configuration (Available for ECE only)
* xref:ecctl_platform_instance-configuration_delete[ecctl platform instance-configuration delete]	 - Deletes an instance configuration (Available for ECE only)
* xref:ecctl_platform_instance-configuration_list[ecctl platform instance-configuration list]	 - Lists the instance configurations (Available for ECE only)
* xref:ecctl_platform_instance-configuration_pull[ecctl platform instance-configuration pull]	 - Downloads instance configuration into a local folder (Available for ECE only)
* xref:ecctl_platform_instance-configuration_show[ecctl platform instance-configuration show]	 - Shows an instance configuration (Available for ECE only)
* xref:ecctl_platform_instance-configuration_update[ecctl platform instance-configuration update]	 - Overwrites an instance configuration (Available for ECE only)
