[#ecctl_platform_repository]
== ecctl platform repository

Manages snapshot repositories

[float]
=== Synopsis

Manages snapshot repositories that are used by Elasticsearch clusters
to perform snapshot operations.

----
ecctl platform repository [flags]
----

[float]
=== Options

----
  -h, --help   help for repository
----

[float]
=== Options inherited from parent commands

----
      --apikey string      API key to use to authenticate (If empty will look for EC_APIKEY environment variable)
      --config string      Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force              Do not ask for confirmation
      --format string      Formats the output using a Go template
      --host string        Base URL to use
      --insecure           Skips all TLS validation
      --message string     A message to set on cluster operation
      --output string      Output format [text|json] (default "text")
      --pass string        Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof              Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet              Suppresses the configuration file used for the run, if any
      --timeout duration   Timeout to use on all HTTP calls (default 30s)
      --trace              Enables tracing saves the trace to trace-20060102150405
      --user string        Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose            Enable verbose mode
----

[float]
=== See also

* xref:ecctl_platform[ecctl platform]	 - Manages the platform
* xref:ecctl_platform_repository_create[ecctl platform repository create]	 - Creates / updates a snapshot repository
* xref:ecctl_platform_repository_delete[ecctl platform repository delete]	 - Deletes a snapshot repositories
* xref:ecctl_platform_repository_list[ecctl platform repository list]	 - Lists all the snapshot repositories
* xref:ecctl_platform_repository_show[ecctl platform repository show]	 - Obtains a snapshot repository config
