[#ecctl_platform_allocator]
== ecctl platform allocator

Manages allocators {ece-icon} (Available for ECE only)

----
ecctl platform allocator [flags]
----

[float]
=== Options

----
  -h, --help   help for allocator
----

[float]
=== Options inherited from parent commands

----
      --api-key string        API key to use to authenticate (If empty will look for EC_API_KEY environment variable)
      --config string         Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force                 Do not ask for confirmation
      --format string         Formats the output using a Go template
      --host string           Base URL to use
      --insecure              Skips all TLS validation
      --message string        A message to set on cluster operation
      --output string         Output format [text|json] (default "text")
      --pass string           Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof                 Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet                 Suppresses the configuration file used for the run, if any
      --region string         Elasticsearch Service region
      --timeout duration      Timeout to use on all HTTP calls (default 30s)
      --trace                 Enables tracing saves the trace to trace-20060102150405
      --user string           Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose               Enable verbose mode
      --verbose-credentials   When set, Authorization headers on the request/response trail will be displayed as plain text
      --verbose-file string   When set, the verbose request/response trail will be written to the defined file
----

[float]
=== SEE ALSO

* xref:ecctl_platform[ecctl platform]	 - Manages the platform {ece-icon} (Available for ECE only)
* xref:ecctl_platform_allocator_list[ecctl platform allocator list]	 - Returns all allocators that have instances or are connected to the platform. Use --all flag or --output json to show all. Use --query to match any of the allocators properties. {ece-icon} (Available for ECE only)
* xref:ecctl_platform_allocator_maintenance[ecctl platform allocator maintenance]	 - Sets the allocator in Maintenance mode {ece-icon} (Available for ECE only)
* xref:ecctl_platform_allocator_metadata[ecctl platform allocator metadata]	 - Manages an allocator's metadata
* xref:ecctl_platform_allocator_search[ecctl platform allocator search]	 - Performs advanced allocator searching {ece-icon} (Available for ECE only)
* xref:ecctl_platform_allocator_show[ecctl platform allocator show]	 - Returns information about the allocator {ece-icon} (Available for ECE only)
* xref:ecctl_platform_allocator_vacate[ecctl platform allocator vacate]	 - Moves all the resources from the specified allocator {ece-icon} (Available for ECE only)
