[#ecctl_deployment]
== ecctl deployment

Manages deployments

----
ecctl deployment [flags]
----

[float]
=== Options

----
  -h, --help   help for deployment
----

[float]
=== Options inherited from parent commands

----
      --api-key string        API key to use to authenticate (If empty will look for EC_API_KEY environment variable)
      --config string         Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force                 Do not ask for confirmation
      --format string         Formats the output using a Go template
      --host string           Base URL to use
      --insecure              Skips all TLS validation
      --message string        A message to set on cluster operation
      --output string         Output format [text|json] (default "text")
      --pass string           Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof                 Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet                 Suppresses the configuration file used for the run, if any
      --region string         Elasticsearch Service region
      --timeout duration      Timeout to use on all HTTP calls (default 30s)
      --trace                 Enables tracing saves the trace to trace-20060102150405
      --user string           Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose               Enable verbose mode
      --verbose-credentials   When set, it will not redact the Authorization headers on the request/response trail
      --verbose-file string   If set, it will write the verbose request/response trail to this file
----

[float]
=== SEE ALSO

* xref:ecctl[ecctl]	 - Elastic Cloud Control
* xref:ecctl_deployment_create[ecctl deployment create]	 - Creates a deployment
* xref:ecctl_deployment_delete[ecctl deployment delete]	 - Deletes a previously shutdown deployment {ece-icon}
* xref:ecctl_deployment_elasticsearch[ecctl deployment elasticsearch]	 - Manages Elasticsearch resources
* xref:ecctl_deployment_list[ecctl deployment list]	 - Lists the platform's deployments
* xref:ecctl_deployment_note[ecctl deployment note]	 - Manages a deployment's notes
* xref:ecctl_deployment_plan[ecctl deployment plan]	 - Manages deployment plans
* xref:ecctl_deployment_resource[ecctl deployment resource]	 - Manages deployment resources
* xref:ecctl_deployment_restore[ecctl deployment restore]	 - Restores a previously shut down deployment and all of its associated sub-resources
* xref:ecctl_deployment_resync[ecctl deployment resync]	 - Resynchronizes the search index and cache for the selected deployment or all
* xref:ecctl_deployment_search[ecctl deployment search]	 - Performs advanced deployment search using the Elasticsearch Query DSL
* xref:ecctl_deployment_show[ecctl deployment show]	 - Shows the specified deployment resources
* xref:ecctl_deployment_shutdown[ecctl deployment shutdown]	 - Shuts down a deployment and all of its associated sub-resources
* xref:ecctl_deployment_template[ecctl deployment template]	 - Interacts with deployment template APIs
* xref:ecctl_deployment_update[ecctl deployment update]	 - Updates a deployment from a file definition, allowing certain flag overrides
