[#ecctl_deployment]
== ecctl deployment

Manages deployments

[float]
=== Synopsis

Manages deployments

----
ecctl deployment [flags]
----

[float]
=== Options

----
  -h, --help   help for deployment
----

[float]
=== Options inherited from parent commands

----
      --apikey string      API key to use to authenticate (If empty will look for EC_APIKEY environment variable)
      --config string      Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force              Do not ask for confirmation
      --format string      Formats the output using a Go template
      --host string        Base URL to use
      --insecure           Skips all TLS validation
      --message string     A message to set on cluster operation
      --output string      Output format [text|json] (default "text")
      --pass string        Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof              Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet              Suppresses the configuration file used for the run, if any
      --timeout duration   Timeout to use on all HTTP calls (default 30s)
      --trace              Enables tracing saves the trace to trace-20060102150405
      --user string        Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose            Enable verbose mode
----

[float]
=== SEE ALSO

* xref:ecctl[ecctl]	 - Elastic Cloud Control
* xref:ecctl_deployment_apm[ecctl deployment apm]	 - Manages APM deployments
* xref:ecctl_deployment_create[ecctl deployment create]	 - Creates a deployment from a file definition, allowing certain flag overrides
* xref:ecctl_deployment_delete[ecctl deployment delete]	 - Deletes a previously stopped deployment from the platform
* xref:ecctl_deployment_elasticsearch[ecctl deployment elasticsearch]	 - Manages Elasticsearch clusters
* xref:ecctl_deployment_kibana[ecctl deployment kibana]	 - Manages Kibana instances
* xref:ecctl_deployment_list[ecctl deployment list]	 - Lists the platform's deployments
* xref:ecctl_deployment_note[ecctl deployment note]	 - Manages a deployment's notes
* xref:ecctl_deployment_plan[ecctl deployment plan]	 - Manages deployment plans
* xref:ecctl_deployment_resource[ecctl deployment resource]	 - Manages deployment resources
* xref:ecctl_deployment_restore[ecctl deployment restore]	 - Restores a previously shut down deployment and all of its associated sub-resources
* xref:ecctl_deployment_search[ecctl deployment search]	 - Performs advanced deployment search using the Elasticsearch Query DSL
* xref:ecctl_deployment_show[ecctl deployment show]	 - Shows the specified deployment resources
* xref:ecctl_deployment_shutdown[ecctl deployment shutdown]	 - Shuts down a deployment and all of its associated sub-resources
* xref:ecctl_deployment_update[ecctl deployment update]	 - Updates a deployment from a file definition, allowing certain flag overrides
