[#ecctl_deployment_elasticsearch_instances]
== ecctl deployment elasticsearch instances

Manages elasticsearch at the instance level

[float]
=== Synopsis

Manages elasticsearch at the instance level

----
ecctl deployment elasticsearch instances [flags]
----

[float]
=== Options

----
  -h, --help   help for instances
----

[float]
=== Options inherited from parent commands

----
      --apikey string      API key to use to authenticate (If empty will look for EC_APIKEY environment variable)
      --config string      Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force              Do not ask for confirmation
      --format string      Formats the output using a Go template
      --host string        Base URL to use
      --insecure           Skips all TLS validation
      --message string     A message to set on cluster operation
      --output string      Output format [text|json] (default "text")
      --pass string        Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof              Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet              Suppresses the configuration file used for the run, if any
      --timeout duration   Timeout to use on all HTTP calls (default 30s)
      --trace              Enables tracing saves the trace to trace-20060102150405
      --user string        Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose            Enable verbose mode
----

[float]
=== SEE ALSO

* xref:ecctl_deployment_elasticsearch[ecctl deployment elasticsearch]	 - Manages Elasticsearch clusters
* xref:ecctl_deployment_elasticsearch_instances_override-capacity[ecctl deployment elasticsearch instances override-capacity]	 - Sets overrides at the instance level, use the --all flag to target all instances
* xref:ecctl_deployment_elasticsearch_instances_pause[ecctl deployment elasticsearch instances pause]	 - Pauses (stops) specific Elasticsearch instances, use the --all flag to target all instances
* xref:ecctl_deployment_elasticsearch_instances_resume[ecctl deployment elasticsearch instances resume]	 - Resumes (starts) specific Elasticsearch instances, use the --all flag to target all instances
* xref:ecctl_deployment_elasticsearch_instances_start-routing[ecctl deployment elasticsearch instances start-routing]	 - Resumes routing on specific Elasticsearch instances, use the --all flag to target all instances
* xref:ecctl_deployment_elasticsearch_instances_stop-routing[ecctl deployment elasticsearch instances stop-routing]	 - Stops routing on specific Elasticsearch instances, use the --all flag to target all instances
