[#ecctl_platform]
== ecctl platform

Manages the platform {ece-icon}

[float]
=== Synopsis

Manages the platform {ece-icon}

----
ecctl platform [flags]
----

[float]
=== Options

----
  -h, --help   help for platform
----

[float]
=== Options inherited from parent commands

----
      --apikey string      API key to use to authenticate (If empty will look for EC_APIKEY environment variable)
      --config string      Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force              Do not ask for confirmation
      --format string      Formats the output using a Go template
      --host string        Base URL to use
      --insecure           Skips all TLS validation
      --message string     A message to set on cluster operation
      --output string      Output format [text|json] (default "text")
      --pass string        Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof              Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet              Suppresses the configuration file used for the run, if any
      --region string      Elasticsearch Service region
      --timeout duration   Timeout to use on all HTTP calls (default 30s)
      --trace              Enables tracing saves the trace to trace-20060102150405
      --user string        Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose            Enable verbose mode
----

[float]
=== SEE ALSO

* xref:ecctl[ecctl]	 - Elastic Cloud Control
* xref:ecctl_platform_allocator[ecctl platform allocator]	 - Manages allocators {ece-icon}
* xref:ecctl_platform_constructor[ecctl platform constructor]	 - Manages constructors {ece-icon}
* xref:ecctl_platform_enrollment-token[ecctl platform enrollment-token]	 - Manages tokens {ece-icon}
* xref:ecctl_platform_info[ecctl platform info]	 - Shows information about the platform {ece-icon}
* xref:ecctl_platform_instance-configuration[ecctl platform instance-configuration]	 - Manages instance configurations {ece-icon}
* xref:ecctl_platform_proxy[ecctl platform proxy]	 - Manages proxies {ece-icon}
* xref:ecctl_platform_repository[ecctl platform repository]	 - Manages snapshot repositories {ece-icon}
* xref:ecctl_platform_role[ecctl platform role]	 - Manages platform roles {ece-icon}
* xref:ecctl_platform_runner[ecctl platform runner]	 - Manages platform runners {ece-icon}
