[#ecctl_platform_constructor]
== ecctl platform constructor

Manages constructors {ece-icon}

----
ecctl platform constructor [flags]
----

[float]
=== Options

----
  -h, --help   help for constructor
----

[float]
=== Options inherited from parent commands

----
      --api-key string        API key to use to authenticate (If empty will look for EC_API_KEY environment variable)
      --config string         Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force                 Do not ask for confirmation
      --format string         Formats the output using a Go template
      --host string           Base URL to use
      --insecure              Skips all TLS validation
      --message string        A message to set on cluster operation
      --output string         Output format [text|json] (default "text")
      --pass string           Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof                 Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet                 Suppresses the configuration file used for the run, if any
      --region string         Elasticsearch Service region
      --timeout duration      Timeout to use on all HTTP calls (default 30s)
      --trace                 Enables tracing saves the trace to trace-20060102150405
      --user string           Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose               Enable verbose mode
      --verbose-credentials   When set, it will not redact the Authorization headers on the request/response trail
      --verbose-file string   If set, it will write the verbose request/response trail to this file
----

[float]
=== SEE ALSO

* xref:ecctl_platform[ecctl platform]	 - Manages the platform {ece-icon}
* xref:ecctl_platform_constructor_list[ecctl platform constructor list]	 - Returns all of the constructors in the platform {ece-icon}
* xref:ecctl_platform_constructor_maintenance[ecctl platform constructor maintenance]	 - Sets/un-sets a constructor's maintenance mode {ece-icon}
* xref:ecctl_platform_constructor_resync[ecctl platform constructor resync]	 - Resynchronizes the search index and cache for the selected constructor or all {ece-icon}
* xref:ecctl_platform_constructor_show[ecctl platform constructor show]	 - Returns information about the constructor with given ID {ece-icon}
