== ecctl deployment elasticsearch plan

Manages Elasticsearch plans

[float]
=== Synopsis

Manages Elasticsearch plans

----
ecctl deployment elasticsearch plan [flags]
----

[float]
=== Options

----
  -h, --help   help for plan
----

[float]
=== Options inherited from parent commands

----
      --apikey string      API key to use to authenticate (If empty will look for EC_APIKEY environment variable)
      --config string      Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force              Do not ask for confirmation
      --format string      Formats the output using a Go template
      --host string        Base URL to use
      --insecure           Skips all TLS validation
      --message string     A message to set on cluster operation
      --output string      Output format [text|json] (default "text")
      --pass string        Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof              Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet              Suppresses the configuration file used for the run, if any
      --timeout duration   Timeout to use on all HTTP calls (default 30s)
      --trace              Enables tracing saves the trace to trace-20060102150405
      --user string        Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose            Enable verbose mode
----

[float]
=== See also

* xref:ecctl_deployment_elasticsearch[ecctl deployment elasticsearch]	 - Manages Elasticsearch clusters
* xref:ecctl_deployment_elasticsearch_plan_cancel[ecctl deployment elasticsearch plan cancel]	 - Cancels the pending plan
* xref:ecctl_deployment_elasticsearch_plan_history[ecctl deployment elasticsearch plan history]	 - Lists the plan history
* xref:ecctl_deployment_elasticsearch_plan_monitor[ecctl deployment elasticsearch plan monitor]	 - Monitors the pending plan
* xref:ecctl_deployment_elasticsearch_plan_reapply[ecctl deployment elasticsearch plan reapply]	 - Reapplies the latest plan attempt, resetting all transient settings
* xref:ecctl_deployment_elasticsearch_plan_update[ecctl deployment elasticsearch plan update]	 - Applies or validates the provided plan and tracks the resulting change attempt
