[#ecctl_user]
== ecctl user

Manages the platform users

[float]
=== Synopsis

Manages the platform users

----
ecctl user [flags]
----

[float]
=== Options

----
  -h, --help   help for user
----

[float]
=== Options inherited from parent commands

----
      --apikey string      API key to use to authenticate (If empty will look for EC_APIKEY environment variable)
      --config string      Config name, used to have multiple configs in $HOME/.ecctl/<env> (default "config")
      --force              Do not ask for confirmation
      --format string      Formats the output using a Go template
      --host string        Base URL to use
      --insecure           Skips all TLS validation
      --message string     A message to set on cluster operation
      --output string      Output format [text|json] (default "text")
      --pass string        Password to use to authenticate (If empty will look for EC_PASS environment variable)
      --pprof              Enables pprofing and saves the profile to pprof-20060102150405
  -q, --quiet              Suppresses the configuration file used for the run, if any
      --timeout duration   Timeout to use on all HTTP calls (default 30s)
      --trace              Enables tracing saves the trace to trace-20060102150405
      --user string        Username to use to authenticate (If empty will look for EC_USER environment variable)
      --verbose            Enable verbose mode
----

[float]
=== See also

* xref:ecctl[ecctl]	 - Elastic Cloud Control
* xref:ecctl_user_create[ecctl user create]	 - Creates a new platform user
* xref:ecctl_user_delete[ecctl user delete]	 - Deletes one or more platform users
* xref:ecctl_user_disable[ecctl user disable]	 - Disables a platform user
* xref:ecctl_user_enable[ecctl user enable]	 - Enables a previously disabled platform user
* xref:ecctl_user_key[ecctl user key]	 - Manages the API keys of a platform user
* xref:ecctl_user_list[ecctl user list]	 - Lists all platform users
* xref:ecctl_user_show[ecctl user show]	 - Shows details of a specified user
* xref:ecctl_user_update[ecctl user update]	 - Updates a platform user
