name: docs-build
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  merge_group: ~
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@v1
